version: "3.9"

services:
  linklapse:
    build: ./app
    container_name: linklapse
    environment:
      - LAB_DOMAIN=linklapse.local
      - DB_PATH=/data/linklapse.db
      - ADMIN_EMAIL=marin.ops@linklapse.local
      - ADMIN_PASS=WinterOps!2026
      - SUPPORT_EMAIL=support.agent@linklapse.local
      - FLAG=WEBVERSE{comment_section_is_the_new_c2}
    extra_hosts:
      linklapse.local: "127.0.0.1"
      id.linklapse.local: "127.0.0.1"
      app.linklapse.local: "127.0.0.1"
      blog.linklapse.local: "127.0.0.1"
      blog-api.linklapse.local: "127.0.0.1"
      chat.linklapse.local: "127.0.0.1"
      ops.linklapse.local: "127.0.0.1"
    ports:
      - "80:80"
    volumes:
      - linklapse_data:/data
    restart: unless-stopped

volumes:
  linklapse_data:
